name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-ci.yml"

  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-ci.yml"

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/aws

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::149600119261:role/github-actions-terraform-role
          aws-region: eu-central-1
          allowed-account-ids: 149600119261

      - name: Verify AWS OIDC identity
        run: aws sts get-caller-identity
      - name: Verify AWS network read access
        run: |
          echo "Verifying least-privilege access to AWS networking resources..."

          aws ec2 describe-vpcs \
            --filters "Name=tag:Name,Values=multicloud-devsecops-dev-vpc" \
            --query 'Vpcs[*].[VpcId,CidrBlock,State]' \
            --output table

          aws ec2 describe-subnets \
            --filters "Name=vpc-id,Values=vpc-0bf5b304850bfd5a8" \
            --query 'Subnets[*].[SubnetId,CidrBlock,MapPublicIpOnLaunch,State]' \
            --output table

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Trivy IaC Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: terraform/aws
          severity: HIGH,CRITICAL
          exit-code: "1"
          ignore-unfixed: true